# Generated by Django 5.0.3 on 2024-04-04 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ki_polls', '0002_kioskorder_beverageorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverageorder',
            name='kiosk_order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='beverage_orders', to='ki_polls.kioskorder'),
            preserve_default=False,
        ),
    ]
